config/routes.rb
Rails.application.routes.draw do
  resources :weathericons
  resources :images
  resources :users
  resources :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  get 'logout', to:'api#logout', as:'logout'
  get 'getWeatherIcons', to:'api#getWeatherIcons', as:'getWeatherIcons'
  get 'getImagesUploaded', to:'api#getImagesUploaded', as:'getImagesUploaded'
  post 'uploadImageByUser', to:'api#uploadImageByUser', as:'uploadImageByUser'
  post 'login', to:'api#login', as:'login'
  post 'updateUserToken', to:'api#updateUserToken', as:'updateUserToken'
  post 'registerUser', to:'api#registerUser', as:'registerUser'
  post 'updateUserData', to:'api#updateUserData', as:'updateUserData'
  post 'getUserData', to:'api#getUserData', as:'getUserData'
  post 'updateUserLatLong', to:'api#updateUserLatLong', as:'updateUserLatLong'
  root to: 'users#index'
  

end

app/models/weathericon.rb
class Weathericon < ApplicationRecord


    has_attached_file :icon
    validates_attachment_size :icon, :less_than => 100.megabytes
    validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png', 'image/jpeg', 'application/pdf']



    def icon_url
        if self.icon
                icon_url = self.icon.url
        else
            icon_url = ""

        end
    end


end

app/controllers/weathericons_controller.rb
class WeathericonsController < ApplicationController
  before_action :set_weathericon, only: %i[ show edit update destroy ]

  # GET /weathericons or /weathericons.json
  def index
    @weathericons = Weathericon.all
  end

  # GET /weathericons/1 or /weathericons/1.json
  def show
  end

  # GET /weathericons/new
  def new
    @weathericon = Weathericon.new
  end

  # GET /weathericons/1/edit
  def edit
  end

  # POST /weathericons or /weathericons.json
  def create
    @weathericon = Weathericon.new(weathericon_params)

    respond_to do |format|
      if @weathericon.save
        format.html { redirect_to weathericons_url, notice: "Weathericon was successfully created." }
        format.json { render :show, status: :created, location: @weathericon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @weathericon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathericons/1 or /weathericons/1.json
  def update
    respond_to do |format|
      if @weathericon.update(weathericon_params)
        format.html { redirect_to weathericons_url, notice: "Weathericon was successfully updated." }
        format.json { render :show, status: :ok, location: @weathericon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @weathericon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathericons/1 or /weathericons/1.json
  def destroy
    @weathericon.destroy

    respond_to do |format|
      format.html { redirect_to weathericons_url, notice: "Weathericon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weathericon
      @weathericon = Weathericon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def weathericon_params
      params.require(:weathericon).permit(:name, :icon)
    end
end

app/helpers/weathericons_helper.rb
module WeathericonsHelper
end

app/views/weathericons/_form.html.erb
     <%= form_with(model: weathericon, multipart: true, local: true) do |form| %>

 
  <% if weathericon.errors.any? %>
    <div id="error_explanation">
      <h2 style="font-size:16px;color:red;"><%= pluralize(weathericon.errors.count, "error") %> prohibieron que el weathericonistrador se guarde:</h2>

      <ul>
        <% weathericon.errors.full_messages.each do |message| %>
          <li style="font-size:14px;color:red;"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
  <label class="col-form-label col-md-2">Name</label>
  <div class="col-md-10">
      <input type="text" name="weathericon[name]" value="<%= @weathericon.name %>" class="form-control">
  </div>
</div>

<div class="form-group row">
  <label class="col-form-label col-md-2">Icon PNG</label>
  <div class="col-md-10">
      <input type="file" name="weathericon[icon]" class="form-control">
      <img src="<%= @weathericon.icon.url %>">
  </div>
</div>




<div class="form-group row">
<label class="col-form-label col-md-2"></label>
<div class="col-md-10">
<button class="btn btn-primary" style="width:100%" type="submit">Guardar</button>
</div>

</div>




<% end %>

app/views/weathericons/edit.html.erb
            <div class="page-wrapper" style="margin-left:0px;">
			
            <div class="content container-fluid">
            
                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="page-title">Weathericons</h3>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                <li class="breadcrumb-item active">Weathericons</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title mb-0">Edit WeatherIcon</h4>
                            </div>
                            <div class="card-body">
                            <%= render 'form', weathericon: @weathericon %>
                            </div>
                        </div>
                    
                    </div>
                </div>
            
            </div>			
        </div>
        <!-- /Main Wrapper -->

app/views/weathericons/index.html.erb
<!-- Page Wrapper -->
<div class="page-wrapper" style="margin-left:0px;">
    <div class="content container-fluid">

<!-- Page Header -->
<div class="page-header">
<div class="row">
  <div class="col">
    <h3 class="page-title">Weather Icons</h3>
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
      <li class="breadcrumb-item active">Weather Icons</li>
    </ul>
  </div>
</div>
</div>
<!-- /Page Header -->

<div class="row">
<div class="col-sm-12">
  <div class="card mb-0">
  <div class="card-header">
  <h4 class="card-title mb-0"><a href="/weathericons/new">+ Add Weathericon </a></h4>
 
</div>
    <div class="card-body">

      <div class="table-responsive">
        <table class="datatable table table-stripped mb-0">
          <thead>
            <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Icon</th>
      
   
            <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
          <% @weathericons.each do |weathericon| %>
            <tr>
            <td><%= weathericon.id %></td> 
            <td><%= weathericon.name %></td>
              <td><img style="width:20px;height:20px;" src="<%= weathericon.icon.url %>"></td>
        
            
              <td><%= link_to 'Edit', edit_weathericon_path(weathericon) %></td>
           
            </tr>
          <% end %>
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

</div>			
</div>
<!-- /Page Wrapper -->

app/views/weathericons/new.html.erb
            <div class="page-wrapper" style="margin-left:0px;">
			
            <div class="content container-fluid">
            
                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="page-title">Weathericons</h3>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                <li class="breadcrumb-item active">Weathericons</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title mb-0">Add WeatherIcon</h4>
                            </div>
                            <div class="card-body">
                            <%= render 'form', weathericon: @weathericon %>
                            </div>
                        </div>
                    
                    </div>
                </div>
            
            </div>			
        </div>
        <!-- /Main Wrapper -->