config/routes.rb
Rails.application.routes.draw do
  resources :weathericons
  resources :images
  resources :users
  resources :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  get 'logout', to:'api#logout', as:'logout'
  get 'getWeatherIcons', to:'api#getWeatherIcons', as:'getWeatherIcons'
  get 'getImagesUploaded', to:'api#getImagesUploaded', as:'getImagesUploaded'
  post 'uploadImageByUser', to:'api#uploadImageByUser', as:'uploadImageByUser'
  post 'login', to:'api#login', as:'login'
  post 'updateUserToken', to:'api#updateUserToken', as:'updateUserToken'
  post 'registerUser', to:'api#registerUser', as:'registerUser'
  post 'updateUserData', to:'api#updateUserData', as:'updateUserData'
  post 'getUserData', to:'api#getUserData', as:'getUserData'
  post 'updateUserLatLong', to:'api#updateUserLatLong', as:'updateUserLatLong'
  root to: 'users#index'
  

end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2 style="font-size:16px;color:red;"><%= pluralize(admin.errors.count, "error") %> prohibieron que el administrador se guarde:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li style="font-size:14px;color:red;"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
  <label class="col-form-label col-md-2">Name</label>
  <div class="col-md-10">
      <input type="text" name="admin[name]" value="<%= @admin.name %>" class="form-control">
  </div>
</div>

<div class="form-group row">
  <label class="col-form-label col-md-2">Email</label>
  <div class="col-md-10">
      <input type="text" name="admin[email]" value="<%= @admin.email %>" class="form-control">
  </div>
</div>


<div class="form-group row">
  <label class="col-form-label col-md-2">Password</label>
  <div class="col-md-10">
      <input type="password" name="admin[password]" class="form-control">
  </div>
</div>
<div class="form-group row">
  <label class="col-form-label col-md-2">Confirm Password</label>
  <div class="col-md-10">
      <input type="password" name="admin[password_confirmation]" class="form-control">
  </div>
</div>
<div class="form-group row">
<label class="col-form-label col-md-2">Access Level</label>
<div class="col-md-10">
  <input type="number" name="admin[level]" value="<%= @admin.level %>" class="form-control">
</div>
</div>


<div class="form-group row">
<label class="col-form-label col-md-2"></label>
<div class="col-md-10">
<button class="btn btn-primary" style="width:100%" type="submit">Guardar</button>
</div>

</div>




<% end %>

app/views/admins/edit.html.erb
            <div class="page-wrapper" style="margin-left:0px;">
			
            <div class="content container-fluid">
            
                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="page-title">Administrators</h3>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                <li class="breadcrumb-item active">Administrators</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title mb-0">Edit Administrator</h4>
                            </div>
                            <div class="card-body">
                            <%= render 'form', admin: @admin %>
                            </div>
                        </div>
                    
                    </div>
                </div>
            
            </div>			
        </div>
        <!-- /Main Wrapper -->

app/views/admins/index.html.erb
<!-- Page Wrapper -->
<div class="page-wrapper" style="margin-left:0px;">
    <div class="content container-fluid">

<!-- Page Header -->
<div class="page-header">
<div class="row">
  <div class="col">
    <h3 class="page-title">Administrators</h3>
    <ul class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
      <li class="breadcrumb-item active">Administrators</li>
    </ul>
  </div>
</div>
</div>
<!-- /Page Header -->

<div class="row">
<div class="col-sm-12">
  <div class="card mb-0">
  <div class="card-header">
  <h4 class="card-title mb-0"><a href="/admins/new">+ Add Administrator </a></h4>
 
</div>
    <div class="card-body">

      <div class="table-responsive">
        <table class="datatable table table-stripped mb-0">
          <thead>
            <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
      
            <th>Access Level</th>
            <th colspan="1"></th>
            </tr>
          </thead>
          <tbody>
          <% @admins.each do |admin| %>
            <tr>
            <td><%= admin.id %></td> 
            <td><%= admin.name %></td>
              <td><%= admin.email %></td>
        
              <td><%= admin.level %></td>
           
              <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
           
            </tr>
          <% end %>
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

</div>			
</div>
<!-- /Page Wrapper -->

app/views/admins/new.html.erb
            <div class="page-wrapper" style="margin-left:0px;">
			
            <div class="content container-fluid">
            
                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="page-title">Administrators</h3>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
                                <li class="breadcrumb-item active">Administrators</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title mb-0">Add Administrator</h4>
                            </div>
                            <div class="card-body">
                            <%= render 'form', admin: @admin %>
                            </div>
                        </div>
                    
                    </div>
                </div>
            
            </div>			
        </div>
        <!-- /Main Wrapper -->